services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kino_kod_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
